targets:
  $default:
    builders:
      dart_json_mapper:
        generate_for:
          # here should be listed entry point files having 'void main()' function
          - lib/main/main.dart
      reflectable:
        generate_for:
          - no/files
      flutter_localizations:
        generate_for:
          - lib/l10n/*.arb