name: flutter_bloc_advance
description: Flutter Bloc Advance Template
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4
  flutter: '3.24.5'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  adaptive_theme:
  cupertino_icons:
  flutter_bloc:
  equatable:
  dart_json_mapper:
  http:
  flutter_form_builder: ^9.5.0
  form_builder_validators: ^11.0.0
  get:
  intl_utils:
  pattern_formatter:
  bloc_concurrency:
  shared_preferences:
  logger: ^2.5.0
  get_storage:
  mockito:
  bloc_test: any
  flutter_stripe: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.25.7
  build_runner:




flutter_secure_storage:
  enabled: true
  class_name: SecureStorage
  main_locale: en

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/mock/
    - assets/images/

flutter_intl:
  enabled: true
